Next.jsのserverサイドのデバッグがうまくいかなかったが、改善したのでその方法
まず、serverサイドのデバッグはattachを使用する。
launchでやろうとしたが、以下のエラーになってしまった。
 basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
           ^^^^^^^
 SyntaxError: missing ) after argument list
で、上記のエラーで検索したら、良い記事見つけて、それで解決できたので以下に記す

まず、このエラーはNext.js 13以降のバグらしい。
Next.jsをデバッグする場合、下記のコマンドが一般的で、このときNext.jsはローカルホストからのアクセスのみを受け付ける。
 NODE_OPTIONS='--inspect' next dev
そのためホスト環境でNext.jsサーバーを起動している場合やDevcontainerでデバッグする場合は問題ないものの、
Docker上でサーバーを動かしている場合、vscodeからコンテナで動いているNext.jsにアクセスしてデバッグすることができなかった。
解決策としては、Next.jsのバージョンをv14.3.0-canary.23以降にする。しかしstableは2024/8/3/時点の14.2.5の為、現実的でない。
そこで、もう一つの解決策、node_modulesのバグの原因となっている場所を直接書き換える。これで治った。

node_modulesがあるディレクトリで、以下のコマンドを実行してバグの該当箇所を書き換える
 sed -Ei '/NODE_OPTIONS.*nodeDebugType.*/s//NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=0.0.0.0:9229`;/' node_modules/next/dist/cli/next-dev.js
このコマンドでは、node_modules/next/dist/cli/next-dev.jsファイル内の下記の行を
 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=${(0, _utils.getDebugPort)() + 1}`;
こちらに書き換えている。
 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=0.0.0.0:9229`;

あとは、今回変更したファイルを参考に修正すれば、うまくいくはずだ。