Docker buildまでできている状態
next.jsの公式リポジトリを参考にした
https://github.com/vercel/next.js/tree/canary/examples/with-docker

npm run devを実行すると、
C:\Users\xehir\repos\whiskyLog\frontend\node_modules\.bin\next:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list

というエラーになりデバッグができない状態